import Head from "next/head";

import {
  Button,
  Heading,
  Picture,
  Icon,
  Input,
  Spacer,
  ButtonIcon,
  Dropdown,
} from "@super2016/components_a";

const OPTIONS = [
  {
    text: "4:00 AM",
    value: 800,
  },
  {
    text: "5:00 AM",
    value: 1000,
  },
  {
    text: "6:00 PM",
    value: 1300,
  },
  {
    text: "7:00 PM",
    value: 1500,
  },
];

export default function Home() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Demostrar controles funcionan.</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <Button>Hola mundo</Button>
    //   <Heading size="md" color="primary">
    //     Contenido heading
    //   </Heading>
    //   <Picture src="https://placeimg.com/400/400/any" width={100} />
    //   <Icon />
    //   <Icon type="arrowRight" />
    //   <Icon type="angleDown" />
    //   <Icon type="angleDown" hasBackground={true} />
    //   <br />
    //   <Input value="ff" placeholder="Nombres" />
    //   <br />
    //   <ButtonIcon />
    //   <br />
    //   <Dropdown onChange={undefined} options={OPTIONS} />
    //   <br />
    //   <Spacer size={8} isVisible />
    //   <br />
    //   <Spacer.Horizontal size={8} isVisible />
    //   <br />
    //   <Spacer.Vertical size={8} isVisible maxHeight={50} />
    // </div>
    <div></div>
  );
}
